import 'package:flutter/material.dart';
import 'package:ielts_ai_trainer/features/speaking/speaking_chat_input_screen.dart';
import 'package:ielts_ai_trainer/shared/enums/test_task.dart';

/// Speaking Part 3 Answer Input Screen.
class SpeakingPart3AnswerInputScreen extends StatefulWidget {
  /// The initial prompt text generated by the question generator screen.
  final String initialPromptText;

  /// The topics used in the practice.
  final List<String> topics;

  const SpeakingPart3AnswerInputScreen({
    super.key,
    required this.initialPromptText,
    required this.topics,
  });

  @override
  State<SpeakingPart3AnswerInputScreen> createState() =>
      _SpeakingPart3AnswerInputScreenState();
}

/// State for SpeakingPart1AnswerInputScreen.
class _SpeakingPart3AnswerInputScreenState
    extends State<SpeakingPart3AnswerInputScreen> {
  @override
  Widget build(BuildContext context) {
    return SpeakingChatInputScreen(
      initialPromptText: widget.initialPromptText,
      topics: widget.topics,
      testTask: TestTask.speakingPart3,
    );
  }
}
