import 'package:flutter/material.dart';
import 'package:ielts_ai_trainer/features/writing/domain/writing_prompt_vo.dart';
import 'package:ielts_ai_trainer/features/writing/writing_answer_input_screen.dart';
import 'package:ielts_ai_trainer/shared/enums/test_task.dart';
import 'package:ielts_ai_trainer/shared/enums/writing_prompt_type.dart';

/// Writing Task 2 Answer Input Screen.
class WritingTask2AnswerInputScreen extends StatefulWidget {
  /// The prompt components generated by the question generator screen.
  final WritingPromptVo writingPrompt;

  /// The topics used to generate the prompt.
  final List<String> topics;

  /// The prompt type used to generate the prompt.
  final WritingPromptType promptType;

  const WritingTask2AnswerInputScreen({
    super.key,
    required this.writingPrompt,
    required this.topics,
    required this.promptType,
  });

  @override
  State<WritingTask2AnswerInputScreen> createState() =>
      _WritingTask2AnswerInputScreenState();
}

/// State for WritingTask2AnswerInputScreen.
class _WritingTask2AnswerInputScreenState
    extends State<WritingTask2AnswerInputScreen> {
  @override
  Widget build(BuildContext context) {
    return WritingAnswerInputScreen(
      writingPrompt: widget.writingPrompt,
      topics: widget.topics,
      testTask: TestTask.writingTask2,
      promptType: widget.promptType,
    );
  }
}
