import 'package:flutter/material.dart';
import 'package:ielts_ai_trainer/features/speaking/speaking_chat_input_screen.dart';
import 'package:ielts_ai_trainer/shared/enums/test_task.dart';

/// Speaking Part 1 Answer Input Screen.
class SpeakingPart1AnswerInputScreen extends StatefulWidget {
  /// The initial prompt text generated by the question generator screen.
  final String initialPromptText;

  /// The topics used in the practice.
  final List<String> topics;

  /// ID issued when the initial prompt was generated.
  final String initialChatId;

  const SpeakingPart1AnswerInputScreen({
    super.key,
    required this.initialPromptText,
    required this.topics,
    required this.initialChatId,
  });

  @override
  State<SpeakingPart1AnswerInputScreen> createState() =>
      _SpeakingPart1AnswerInputScreenState();
}

/// State for SpeakingPart1AnswerInputScreen.
class _SpeakingPart1AnswerInputScreenState
    extends State<SpeakingPart1AnswerInputScreen> {
  @override
  Widget build(BuildContext context) {
    return SpeakingChatInputScreen(
      initialPromptText: widget.initialPromptText,
      topics: widget.topics,
      testTask: TestTask.speakingPart1,
      initialChatId: widget.initialChatId,
    );
  }
}
