import 'package:collection/collection.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:ielts_ai_trainer/app/router_extra.dart';
import 'package:ielts_ai_trainer/app/theme/app_colors.dart';
import 'package:ielts_ai_trainer/app/theme/app_styles.dart';
import 'package:ielts_ai_trainer/features/speaking/chat_row.dart';
import 'package:ielts_ai_trainer/features/speaking/domain/speaking_answer_repository.dart';
import 'package:ielts_ai_trainer/features/speaking/speaking_chat_input_controller.dart';
import 'package:ielts_ai_trainer/features/speaking/speaking_routes.dart';
import 'package:ielts_ai_trainer/shared/database/app_database.dart';
import 'package:ielts_ai_trainer/shared/enums/test_task.dart';
import 'package:ielts_ai_trainer/shared/utils/dialog.dart';
import 'package:ielts_ai_trainer/shared/views/base_screen_scaffold.dart';
import 'package:ielts_ai_trainer/shared/views/hover_highlight_text_field.dart';
import 'package:ielts_ai_trainer/shared/views/texts.dart';
import 'package:provider/provider.dart';

/// An answer input view for the Speaking Part 1 & 3 Answer Input Screens.
class SpeakingChatInputScreen extends StatefulWidget {
  /// The initial prompt text generated by the question generator screen.
  final String initialPromptText;

  /// The topics used in the practice.
  final List<String> topics;

  /// The task type.
  final TestTask testTask;

  const SpeakingChatInputScreen({
    super.key,
    required this.initialPromptText,
    required this.topics,
    required this.testTask,
  });

  @override
  State<SpeakingChatInputScreen> createState() =>
      _SpeakingChatInputScreenState();
}

/// State for SpeakingChatInputScreen.
class _SpeakingChatInputScreenState extends State<SpeakingChatInputScreen> {
  late final SpeakingChatInputController _ctrl;

  /// Controller for the message input text field.
  final TextEditingController _textCtrl = TextEditingController();

  /// Controller for scrolling the message list.
  final ScrollController _scrollCtrl = ScrollController();

  /// Returns the screen title based on the task type.
  String get _screenTitle {
    return widget.testTask == TestTask.speakingPart1
        ? 'Speaking Part 1'
        : 'Speaking Part 3';
  }

  @override
  void initState() {
    super.initState();

    _ctrl = SpeakingChatInputController(
      speakingAnswerRepository: SpeakingAnswerRepository(
        context.read<AppDatabase>(),
      ),
      promptText: widget.initialPromptText,
      topics: widget.topics,
      testTask: widget.testTask,
    );

    _ctrl.addMessage(false, widget.initialPromptText);

    _ctrl.startTimer();
  }

  @override
  void dispose() {
    _ctrl.cancelTimer();
    super.dispose();
  }

  /// Called when the Recording button is pressed.
  void _onPressedRecording(int index) async {
    if (_ctrl.isRecording) {
      await _ctrl.stopRecording();
    } else {
      await _ctrl.startRecording(index);
    }
  }

  /// Called when the Play button is pressed.
  void _onPressedPlay(int index) async {
    if (_ctrl.isPlaying) {
      await _ctrl.stopPlaying();
    } else {
      await _ctrl.startPlaying(index);
    }
  }

  /// Called when the Send button is pressed.
  void _onPressedSend() async {
    // Adds a message.
    final userMessage = _ctrl.currentMessageText;
    _ctrl.addMessage(true, userMessage);

    // Clears the input field.
    _ctrl.currentMessageText = '';
    _textCtrl.clear();

    // Scrolls to the user's message.
    _scrollToBottom();

    // Generates and adds the AI's reply.
    await _ctrl.generateNextPrompt(userMessage);

    // Scrolls to the AI's message.
    _scrollToBottom();
  }

  /// Called when the Submit button is pressed.
  void _onPressedSubmit() async {
    // Confirm whether to submit the answer.
    final confirmed = await showConfirmDialog(
      context,
      'Submit your answer?',
      '',
    );
    if (confirmed == null || !confirmed) {
      return;
    }

    if (!mounted) {
      // If state has been destroyed, context cannot be used, so return
      return;
    }

    // Save the answer
    late int id;
    try {
      id = await _ctrl.saveUserAnswer();
    } catch (e, stackTrace) {
      showAlertDialog(context, e.toString(), stackTrace.toString());
      return;
    }

    // Navigates to the result screen.
    final extra = RouterExtra({'id': id});
    if (widget.testTask == TestTask.speakingPart1) {
      context.go(speakingPart1ResultScreenRoutePath, extra: extra);
    } else if (widget.testTask == TestTask.speakingPart3) {
      context.go(speakingPart3ResultScreenRoutePath, extra: extra);
    }
  }

  /// Scrolls the message list to the bottom.
  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scrollCtrl.hasClients) {
        _scrollCtrl.animateTo(
          _scrollCtrl.position.maxScrollExtent,
          duration: Duration(milliseconds: 200),
          curve: Curves.easeOut,
        );
      }
    });
  }

  /// Called when the Cancel button is pressed.
  void _onPressedCancel() async {
    // Confirm whether to stop practicing.
    final confirmed = await showConfirmDialog(context, 'Stop to practice?', '');
    if (confirmed == null || !confirmed) {
      return;
    }

    // Delete all temporary file.
    _ctrl.deleteAllTemporaryRecordingFiles();

    if (!mounted) {
      // If state has been destroyed, context cannot be used, so return
      return;
    }

    // Navigates to the question generator screen.
    final extra = RouterExtra({
      'promptText': widget.initialPromptText,
      'topics': widget.topics,
    });
    if (widget.testTask == TestTask.speakingPart1) {
      context.go(speakingPart1QuestionGeneratorScreenRoutePath, extra: extra);
    } else if (widget.testTask == TestTask.speakingPart3) {
      context.go(speakingPart3QuestionGeneratorScreenRoutePath, extra: extra);
    }
  }

  /// Called when the input message text changes.
  void _onChangedText(String? value) {
    if (value != null) {
      _ctrl.currentMessageText = value;
    }
  }

  @override
  Widget build(BuildContext context) {
    return BaseScreenScaffold(
      showHeader: false,
      body: AnimatedBuilder(
        animation: _ctrl,
        builder: (context, _) {
          return Column(
            children: [
              SizedBox(height: 24),
              // Screen title and Elapsed time
              Padding(
                padding: EdgeInsets.symmetric(
                  horizontal: AppStyles.screenPadding,
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    // Screen Title
                    ScreenTitleText(_screenTitle),
                    // Elapsed time
                    Text(_ctrl.elapsedAsText),
                  ],
                ),
              ),
              SizedBox(height: 20),
              // Messages
              Expanded(
                child: ListView(
                  controller: _scrollCtrl,
                  children: [
                    Padding(
                      padding: EdgeInsets.symmetric(
                        horizontal: AppStyles.screenPadding,
                      ),
                      child: Column(
                        children: _ctrl.messages.mapIndexed((i, message) {
                          return Padding(
                            padding: const EdgeInsets.only(bottom: 20),
                            child: ChatRow(
                              key: ValueKey(i),
                              isUser: message.isUser,
                              text: message.text,
                              index: i,
                              onPressedPlay: _ctrl.isPlayButtonEnabledAt(i)
                                  ? _onPressedPlay
                                  : null,
                              onPressedRecording:
                                  _ctrl.isRecordingButtonEnabledAt(i)
                                  ? _onPressedRecording
                                  : null,
                              showPlayButton: _ctrl.isShowPlayButtonAt(i),
                              recordingButtonLabel: _ctrl
                                  .getRecordingButtonLabelAt(i),
                              playingButtonLabel: _ctrl.getPlayButtonLabelAt(i),
                              showRecordingButton: true,
                            ),
                          );
                        }).toList(),
                      ),
                    ),
                  ],
                ),
              ),
              // Message input field
              Padding(
                padding: EdgeInsets.symmetric(
                  horizontal: AppStyles.screenPadding,
                ),
                child: Column(
                  children: [
                    Row(
                      children: [
                        Expanded(
                          child: HoverHighlightTextField(
                            enabled: _ctrl.isControlsEnabled,
                            onChanged: _onChangedText,
                            controller: _textCtrl,
                          ),
                        ),
                        SizedBox(width: 8),
                        FilledButton(
                          onPressed:
                              _ctrl.isMessageInputEnabled &&
                                  _ctrl.isControlsEnabled
                              ? _onPressedSend
                              : null,
                          child: const Text('Send'),
                        ),
                      ],
                    ),
                    SizedBox(height: 20),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        // Messages to indicate the requried reply.
                        Row(
                          children: [
                            Text(
                              (_ctrl.replyCountUntilSubmitEnabled > 0)
                                  ? '${_ctrl.replyCountUntilSubmitEnabled} more replies required to submit.'
                                  : '',
                            ),
                          ],
                        ),
                        // Cancel and Submit buttons
                        Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: [
                            OutlinedButton(
                              onPressed: _ctrl.isControlsEnabled
                                  ? _onPressedCancel
                                  : null,
                              style: ButtonStyle(
                                side: WidgetStateProperty.resolveWith((states) {
                                  if (states.contains(WidgetState.hovered)) {
                                    return BorderSide(
                                      color: AppColors.focusColor,
                                      width: 1,
                                    );
                                  }
                                  return BorderSide(
                                    color: AppColors.checkboxBorderColor,
                                    width: 1,
                                  );
                                }),
                              ),
                              child: const Text('Cancel'),
                            ),
                            SizedBox(width: 20),
                            FilledButton(
                              onPressed:
                                  _ctrl.isSubmitButtonEnabled &&
                                      _ctrl.isControlsEnabled
                                  ? _onPressedSubmit
                                  : null,
                              child: const Text('Submit'),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              SizedBox(height: AppStyles.screenBottomPadding),
            ],
          );
        },
      ),
    );
  }
}
