import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:ielts_ai_trainer/app/router_extra.dart';
import 'package:ielts_ai_trainer/app/theme/app_colors.dart';
import 'package:ielts_ai_trainer/app/theme/app_styles.dart';
import 'package:ielts_ai_trainer/features/speaking/domain/speaking_answer_repository.dart';
import 'package:ielts_ai_trainer/features/speaking/speaking_part2_answer_input_controller.dart';
import 'package:ielts_ai_trainer/features/speaking/speaking_routes.dart';
import 'package:ielts_ai_trainer/shared/database/app_database.dart';
import 'package:ielts_ai_trainer/shared/utils/dialog.dart';
import 'package:ielts_ai_trainer/shared/views/base_screen_scaffold.dart';
import 'package:ielts_ai_trainer/shared/views/buttons.dart';
import 'package:ielts_ai_trainer/shared/views/hover_highlight_text_field.dart';
import 'package:ielts_ai_trainer/shared/views/texts.dart';
import 'package:provider/provider.dart';

/// Speaking Part 2 Answer Input Screen.
class SpeakingPart2AnswerInputScreen extends StatefulWidget {
  /// The prompt text generated by the question generator screen.
  final String promptText;

  /// The topics used in the practice.
  final List<String> topics;

  const SpeakingPart2AnswerInputScreen({
    super.key,
    required this.promptText,
    required this.topics,
  });

  @override
  State<SpeakingPart2AnswerInputScreen> createState() =>
      _SpeakingPart2AnswerInputScreenState();
}

/// State for SpeakingPart2AnswerInputScreen.
class _SpeakingPart2AnswerInputScreenState
    extends State<SpeakingPart2AnswerInputScreen> {
  late final SpeakingPart2AnswerInputController _ctrl;

  @override
  void initState() {
    super.initState();

    _ctrl = SpeakingPart2AnswerInputController(
      speakingAnswerRepository: SpeakingAnswerRepository(
        context.read<AppDatabase>(),
      ),
      promptText: widget.promptText,
      topics: widget.topics,
    );

    _ctrl.startTimer();
  }

  @override
  void dispose() {
    _ctrl.cancelTimer();
    super.dispose();
  }

  /// Called when the note text changes.
  void _onChangedNoteText(String value) {
    _ctrl.noteText = value;
  }

  /// Called when the answer text changes.
  void _onChangedAnswerText(String value) {
    _ctrl.answerText = value;
  }

  /// Called when the submit button is pressed.
  void _onPressedSubmit() async {
    // Confirm whether to submit the answer.
    final confirmed = await showSubmitAnswerDialog(context);
    if (confirmed == null || !confirmed) {
      return;
    }

    if (!mounted) {
      // If state has been destroyed, context cannot be used, so return
      return;
    }

    // Save the answer
    late int id;
    try {
      id = await _ctrl.saveUserAnswer();
    } catch (e, stackTrace) {
      if (!mounted) {
        // avoid context across async gaps.
        return;
      }
      showAlertDialog(context, e.toString(), stackTrace.toString());
      return;
    }

    if (!mounted) {
      // avoid context across async gaps.
      return;
    }

    // Navigates to the result screen.
    context.go(
      speakingPart2ResultScreenRoutePath,
      extra: RouterExtra({'id': id}),
    );
  }

  /// Called when the cancel button is pressed.
  void _onPressedCancel() async {
    // Confirm whether to stop practicing.
    final confirmed = await showQuitPracticeDialog(context);
    if (confirmed == null || !confirmed) {
      return;
    }

    // Delete the recorded file.
    _ctrl.deleteRecordingFile();

    if (!mounted) {
      // If state has been destroyed, context cannot be used, so return
      return;
    }

    // Navigates to the question generator screen.
    final extra = RouterExtra({
      'promptText': widget.promptText,
      'topics': widget.topics,
    });
    context.go(speakingPart2QuestionGeneratorScreenRoutePath, extra: extra);
  }

  /// Called when the Lock checkbox state changes.
  void _onChangedLock(bool? value) {
    _ctrl.isNoteLocked = value ?? false;
  }

  /// Called when the Recorrding button is pressed.
  void _onRecordingButtonPressed() async {
    if (!_ctrl.isRecording && !_ctrl.isReRecording) {
      await _ctrl.startRecording();
    } else if (_ctrl.isRecording || _ctrl.isReRecording) {
      await _ctrl.stopRecording();
    }
  }

  /// Called when the Play button is pressed.
  void _onPlayButtonPressed() async {
    if (_ctrl.isStop) {
      await _ctrl.startPlaying();
    } else {
      await _ctrl.stopPlaying();
    }
  }

  @override
  Widget build(BuildContext context) {
    return BaseScreenScaffold(
      showHeader: false,
      body: AnimatedBuilder(
        animation: _ctrl,
        builder: (context, _) {
          return SingleChildScrollView(
            child: Padding(
              padding: EdgeInsets.symmetric(
                horizontal: AppStyles.screenPadding,
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  SizedBox(height: 24),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      // Screen title
                      ScreenTitleText('Speaking Part 2'),
                      // Elapsed time
                      Text(_ctrl.elapsedAsText),
                    ],
                  ),
                  SizedBox(height: 20),
                  // Prompt text
                  Text(widget.promptText),
                  SizedBox(height: 20),
                  // Note
                  Row(
                    children: [
                      FieldLabel('Note'),
                      SizedBox(
                        width: 160,
                        child: Container(
                          padding: EdgeInsets.only(left: 20),
                          child: Text('Remaining: ${_ctrl.remainingAsText}'),
                        ),
                      ),
                      SizedBox(
                        width: 150,
                        child: Row(
                          children: [
                            Checkbox(
                              visualDensity: const VisualDensity(
                                vertical: -3,
                                // horizontal: -4,
                              ),
                              checkColor: Colors.white,
                              activeColor: AppColors.focusColor,
                              side: BorderSide(
                                color: AppColors.checkboxBorderColor,
                                width: 2,
                              ),
                              value: _ctrl.isNoteLocked,
                              onChanged: _onChangedLock,
                              semanticLabel: 'Lock the Note',
                            ),
                            Text('Lock'),
                          ],
                        ),
                      ),
                    ],
                  ),
                  Container(
                    margin: EdgeInsets.only(bottom: 8),
                    child: Text(
                      'Input will be locked when time runs out. Uncheck "Lock" to edit again.',
                      style: AppStyles.helperTextStyle,
                    ),
                  ),
                  HoverHighlightTextField(
                    enabled: _ctrl.isNoteEnabled,
                    minLines: 3, // always show at least 3 lines
                    maxLines: null, // expands automatically
                    keyboardType: TextInputType.multiline,
                    hintText: 'Type your note...',
                    onChanged: _onChangedNoteText,
                    style: TextStyle(color: AppColors.textColor),
                  ),
                  SizedBox(height: 20),
                  // Answer
                  Container(
                    margin: EdgeInsets.only(bottom: 8),
                    child: FieldLabel('Answer'),
                  ),
                  Stack(
                    children: [
                      HoverHighlightTextField(
                        minLines: 5, // always show at least 5 lines
                        maxLines: null, // expands automatically
                        keyboardType: TextInputType.multiline,
                        hintText: 'Type your answer...',
                        onChanged: _onChangedAnswerText,
                        style: TextStyle(color: AppColors.textColor),
                      ),
                      // Recording button and Play button
                      Positioned(
                        right: 10,
                        bottom: 10,
                        child: Row(
                          children: [
                            buildOutlinedButton(
                              _ctrl.isRecording || _ctrl.isReRecording
                                  ? 'Stop'
                                  : 'Recording',
                              onPressed: _ctrl.isRecordingButtonEnabled
                                  ? _onRecordingButtonPressed
                                  : null,
                            ),
                            if (_ctrl.isRecorded || _ctrl.isReRecording)
                              SizedBox(width: 10),
                            if (_ctrl.isRecorded || _ctrl.isReRecording)
                              buildOutlinedButton(
                                _ctrl.isStop ? 'Play' : 'Stop',
                                onPressed:
                                    _ctrl.isRecording || _ctrl.isReRecording
                                    ? null
                                    : _onPlayButtonPressed,
                              ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  // Cancel and Submit buttons
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Padding(
                        padding: const EdgeInsets.only(top: 8),
                        child: Text(_ctrl.getWordCountAsText()),
                      ),
                      Padding(
                        padding: const EdgeInsets.only(top: 20),
                        child: Row(
                          children: [
                            TextButton(
                              onPressed: _onPressedCancel,
                              style: ButtonStyle(
                                backgroundColor: WidgetStatePropertyAll(
                                  AppColors.chipBackground,
                                ),
                              ),
                              child: const Text('Quit'),
                            ),
                            SizedBox(width: 12),
                            FilledButton(
                              onPressed: _ctrl.isSubmitButtonEnabled
                                  ? _onPressedSubmit
                                  : null,
                              child: const Text('Submit'),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  SizedBox(height: AppStyles.screenBottomPadding),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}
