import 'package:flutter/material.dart';
import 'package:ielts_ai_trainer/features/writing/writing_answer_input_screen.dart';
import 'package:ielts_ai_trainer/shared/enums/test_task.dart';
import 'package:ielts_ai_trainer/shared/enums/writing_prompt_type.dart';

/// Writing Task 1 Answer Input Screen.
class WritingTask1AnswerInputScreen extends StatefulWidget {
  /// The prompt text generated by the question generator screen.
  final String promptText;

  /// The topics used to generate the prompt.
  final List<String> topics;

  /// The question type used to generate the prompt.
  final WritingPromptType promptType;

  const WritingTask1AnswerInputScreen({
    super.key,
    required this.promptText,
    required this.topics,
    required this.promptType,
  });

  @override
  State<WritingTask1AnswerInputScreen> createState() =>
      _WritingTask1AnswerInputScreenState();
}

/// State for WritingTask1AnswerInputScreen.
class _WritingTask1AnswerInputScreenState
    extends State<WritingTask1AnswerInputScreen> {
  @override
  Widget build(BuildContext context) {
    return WritingAnswerInputScreen(
      promptText: widget.promptText,
      topics: widget.topics,
      testTask: TestTask.writingTask1,
      promptType: widget.promptType,
    );
  }
}
