import 'package:flutter/material.dart';
import 'package:ielts_ai_trainer/features/writing/writing_answer_input_screen.dart';
import 'package:ielts_ai_trainer/shared/enums/test_task.dart';
import 'package:ielts_ai_trainer/shared/enums/writing_task2_essay_type.dart';

/// Writing Task 2 Answer Input Screen.
class WritingTask2AnswerInputScreen extends StatefulWidget {
  /// The prompt text generated by the question generator screen.
  final String promptText;

  /// The topics used to generate the prompt.
  final List<String> topics;

  /// The essay type used to generate the prompt.
  final WritingTask2EssayType essayType;

  const WritingTask2AnswerInputScreen({
    super.key,
    required this.promptText,
    required this.topics,
    required this.essayType,
  });

  @override
  State<WritingTask2AnswerInputScreen> createState() =>
      _WritingTask2AnswerInputScreenState();
}

/// State for WritingTask2AnswerInputScreen.
class _WritingTask2AnswerInputScreenState
    extends State<WritingTask2AnswerInputScreen> {
  @override
  Widget build(BuildContext context) {
    return WritingAnswerInputScreen(
      promptText: widget.promptText,
      topics: widget.topics,
      testTask: TestTask.writingTask2,
      essayType: widget.essayType,
    );
  }
}
